=== raycast/extensions/extensions/youversion-suggest/assets/data/schemas/schema-bible.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Bible data for a specific language",
  "type": "object",
  "properties": {
    "books": {
      "description": "The list of Bible books available in this language",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "The ID used by YouVersion to uniquely identify this book",
            "type": "string",
            "pattern": "^([a-z]{3}|[1-3][a-z]{2})$"
          },
          "name": {
            "description": "The name of this book in the respective language",
            "type": "string"
          }
        },
        "required": ["id", "name"],
        "additionalProperties": false
      }
    },
    "language": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The ISO 639-3 code for this language",
          "type": "string",
          "pattern": "^[a-z]{3}(_[a-z]{2,3})?$"
        },
        "name": {
          "description": "The name of this language as written in said language",
          "type": "string"
        }
      }
    },
    "default_version": {
      "description": "The default Bible version to use for this language",
      "type": "integer",
      "minimum": 1
    },
    "versions": {
      "description": "The list of Bible versions for this language",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "full_name": {
            "description": "The full, unabbreviated name of this version",
            "type": "string"
          },
          "id": {
            "description": "The ID used by YouVersion to uniquely identify this version",
            "type": "integer",
            "minimum": 1
          },
          "name": {
            "description": "The acronym for this version",
            "type": "string"
          }
        },
        "required": ["id", "name"],
        "additionalProperties": false
      }
    }
  },
  "required": ["books", "default_version", "versions"],
  "additionalProperties": false
}

=== raycast/extensions/extensions/youversion-suggest/assets/data/bible/bible-ind.json
{
  "books": [
    {
      "id": "gen",
      "name": "Kejadian"
    },
    {
      "id": "exo",
      "name": "Keluaran"
    },
    {
      "id": "lev",
      "name": "Imamat"
    },
    {
      "id": "num",
      "name": "Bilangan"
    },
    {
      "id": "deu",
      "name": "Ulangan"
    },
    {
      "id": "jos",
      "name": "Yosua"
    },
    {
      "id": "jdg",
      "name": "Hakim-hakim"
    },
    {
      "id": "rut",
      "name": "Rut"
    },
    {
      "id": "1sa",
      "name": "1 Samuel"
    },
    {
      "id": "2sa",
      "name": "2 Samuel"
    },
    {
      "id": "1ki",
      "name": "1 Raja-raja"
    },
    {
      "id": "2ki",
      "name": "2 Raja-raja"
    },
    {
      "id": "1ch",
      "name": "1 Tawarikh"
    },
    {
      "id": "2ch",
      "name": "2 Tawarikh"
    },
    {
      "id": "ezr",
      "name": "Ezra"
    },
    {
      "id": "neh",
      "name": "Nehemia"
    },
    {
      "id": "est",
      "name": "Ester"
    },
    {
      "id": "job",
      "name": "Ayub"
    },
    {
      "id": "psa",
      "name": "Mazmur"
    },
    {
      "id": "pro",
      "name": "Amsal"
    },
    {
      "id": "ecc",
      "name": "Pengkhotbah"
    },
    {
      "id": "sng",
      "name": "Kidung Agung"
    },
    {
      "id": "isa",
      "name": "Yesaya"
    },
    {
      "id": "jer",
      "name": "Yeremia"
    },
    {
      "id": "lam",
      "name": "Ratapan"
    },
    {
      "id": "ezk",
      "name": "Yehezkiel"
    },
    {
      "id": "dan",
      "name": "Daniel"
    },
    {
      "id": "hos",
      "name": "Hosea"
    },
    {
      "id": "jol",
      "name": "Y\"oel"
    },
    {
      "id": "amo",
      "name": "Amos"
    },
    {
      "id": "oba",
      "name": "Obaja"
    },
    {
      "id": "jon",
      "name": "Yunus"
    },
    {
      "id": "mic",
      "name": "Mikha"
    },
    {
      "id": "nam",
      "name": "Nahum"
    },
    {
      "id": "hab",
      "name": "Habakuk"
    },
    {
      "id": "zep",
      "name": "Zefanya"
    },
    {
      "id": "hag",
      "name": "Hagai"
    },
    {
      "id": "zec",
      "name": "Zakharia"
    },
    {
      "id": "mal",
      "name": "Maleakhi"
    },
    {
      "id": "mat",
      "name": "Matius"
    },
    {
      "id": "mrk",
      "name": "Markus"
    },
    {
      "id": "luk",
      "name": "Lukas"
    },
    {
      "id": "jhn",
      "name": "Yohanes"
    },
    {
      "id": "act",
      "name": "Kisah Para Rasul"
    },
    {
      "id": "rom",
      "name": "Roma"
    },
    {
      "id": "1co",
      "name": "1 Korintus"
    },
    {
      "id": "2co",
      "name": "2 Korintus"
    },
    {
      "id": "gal",
      "name": "Galatia"
    },
    {
      "id": "eph",
      "name": "Efesus"
    },
    {
      "id": "php",
      "name": "Filipi"
    },
    {
      "id": "col",
      "name": "Kolose"
    },
    {
      "id": "1th",
      "name": "1 Tesalonika"
    },
    {
      "id": "2th",
      "name": "2 Tesalonika"
    },
    {
      "id": "1ti",
      "name": "1 Timotius"
    },
    {
      "id": "2ti",
      "name": "2 Timotius"
    },
    {
      "id": "tit",
      "name": "Titus"
    },
    {
      "id": "phm",
      "name": "Filemon"
    },
    {
      "id": "heb",
      "name": "Ibrani"
    },
    {
      "id": "jas",
      "name": "Yakobus"
    },
    {
      "id": "1pe",
      "name": "1 Petrus"
    },
    {
      "id": "2pe",
      "name": "2 Petrus"
    },
    {
      "id": "1jn",
      "name": "1 Yohanes"
    },
    {
      "id": "2jn",
      "name": "2 Yohanes"
    },
    {
      "id": "3jn",
      "name": "3 Yohanes"
    },
    {
      "id": "jud",
      "name": "Yudas"
    },
    {
      "id": "rev",
      "name": "Wahyu"
    }
  ],
  "default_version": 306,
  "language": {
    "id": "ind",
    "name": "Bahasa Indonesia"
  },
  "versions": [
    {
      "full_name": "Alkitab dalam Bahasa Indonesia Masa Kini",
      "id": 27,
      "name": "BIMK"
    },
    {
      "full_name": "Perjanjian Baru: Versi Mudah Dibaca",
      "id": 199,
      "name": "AMD"
    },
    {
      "full_name": "Alkitab Terjemahan Baru",
      "id": 306,
      "name": "TB"
    },
    {
      "full_name": "Terjemahan Sederhana Indonesia",
      "id": 320,
      "name": "TSI"
    },
    {
      "full_name": "Firman Allah Yang Hidup",
      "id": 2727,
      "name": "FAYH"
    },
    {
      "full_name": "Alkitab Terjemahan Lama",
      "id": 2861,
      "name": "LAI-TL"
    },
    {
      "full_name": "Indonesian Tazi NT Study Bible",
      "id": 2862,
      "name": "INOTAZI"
    },
    {
      "full_name": "Perjanjian Baru Terjemahan Baru Edisi 2",
      "id": 2863,
      "name": "PBTB2"
    }
  ]
}
